disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - identifier_name
  - line_length
  - nesting
  - type_body_length
  - type_name
  - large_tuple
  - function_parameter_count
  - implicit_return

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - duplicate_imports
  - empty_count
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - generic_type_name
  - identical_operands
  - implicit_getter
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_type_annotation
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - unused_capture_list
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - yoda_condition

included:
  - Rick&Morty

colon:
  apply_to_dictionaries: false

